codecov:
  require_ci_to_pass: no

github_checks:
  annotations: false

coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project:
      default: false
    patch:
      default:
        if_not_found: success
        informational: true
        only_pulls: false
    fxa-auth-server:
      target: auto
      flags:
        - fxa-auth-server
    fxa-customs-server:
      target: auto
      flags:
        - fxa-customs-server

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: false

flags:
  fxa-auth-server:
    paths:
      - packages/fxa-auth-server
    carryforward: true
  fxa-customs-server:
    paths:
      - packages/fxa-customs-server
    carryforward: true
